- name: Provision AWS EC2 instance(s)
  tags: "ec2, provision_ec2"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws_credentials.yaml
  roles:
    - ec2

- name: Setup Full Monitoring stack.
  tags: "monitoring"
  hosts: monitor
  become: true
  gather_facts: true
  pre_tasks:
    - name: update the package index
      apt:
        update_cache: true
        upgrade: true
  roles:
    # - node_exporter
    # - alertmanager
    - prometheus
    # - grafana
    # - webserver