- name: Provision AWS EC2 instance(s)
  tags: "ec2, provision_ec2"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws_credentials.yaml
  roles:
    - ec2

- name: Setup Full Monitoring stack.
  tags: "monitoring"
  hosts: all
  gather_facts: false
  roles:
    - node_exporter