- name: uninstall alert manager
  service:
    name: "{{service_name}}"
    state: stopped
    enabled: no

- name: remove the alertmanager files.
  file:
    path: "{{item}}"
    state: absent

  with_items:
    - "/etc/systemd/system/{{service_name}}.service"
    - "/usr/local/bin/alertmanager"
    - "/data/alertmanager"
  ignore_errors: true

- name: reload the systemd
  systemd:
    daemon_reload: yes
  ignore_errors: true

- name: remove {{user_name}} user
  user:
    name: "{{user_name}}"
    state: absent
    remove: yes
  ignore_errors: true

- name: remove {{group_name}} group
  group:
    name: "{{group_name}}"
    state: absent

- name: Check if alert manager binary is removed
  command: which {{service_name}}
  register: which_result
  ignore_errors: true

- name: "print a debug message."
  debug:
    msg: "This is the output of the result: {{which_result}}"
